### ISSUE TITLE
"'NoneType' object is not callable" when importing bambou.contextual.context

### ISSUE THREAD

**Issue by jjtykkyl** [nuagenetworks/bambou#7]
Hi,

I try to debug my integration with Nuage but I keep getting the "'NoneType' object is not callable" error when I'm trying to import the library in debug mode. Do you have any idea why? Stacktrace below:

```
PYDEV DEBUGGER WARNING:
sys.settrace() should not be used when the debugger is being used.
This may cause the debugger to stop working correctly.
If this is needed, please check: 
http://pydev.blogspot.com/2007/06/why-cant-pydev-debugger-work-with.html
to see how to restore the debug tracing back correctly.
Call Location:
  File "/Users/Joona/workspace/bdn/venv/lib/python2.7/site-packages/bambou/contextual/decorators.py", line 647, in decorate_assignment
    sys.settrace(tracer)

Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd_comm.py", line 1071, in doIt
    result = pydevd_vars.evaluateExpression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd_vars.py", line 344, in evaluateExpression
    Exec(expression, updated_globals, frame.f_locals)
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd_exec.py", line 3, in Exec
    exec exp in global_vars, local_vars
  File "<string>", line 1, in <module>
  File "/Users/Joona/workspace/bdn/venv/lib/python2.7/site-packages/bambou/__init__.py", line 53, in <module>
    from bambou.nurest_session import NURESTSession
  File "/Users/Joona/workspace/bdn/venv/lib/python2.7/site-packages/bambou/nurest_session.py", line 8, in <module>
    from bambou.contextual import context
  File "/Users/Joona/workspace/bdn/venv/lib/python2.7/site-packages/bambou/contextual/context.py", line 83, in <module>
    class State(_ClassDelegate):
  File "/Users/Joona/workspace/bdn/venv/lib/python2.7/site-packages/bambou/contextual/decorators.py", line 690, in __init__
    return supr()(cls, name, bases, cdict, supr)
  File "/Users/Joona/workspace/bdn/venv/lib/python2.7/site-packages/bambou/contextual/decorators.py", line 672, in super_next
    yield getattr(c, attr).im_func
  File "/Users/Joona/workspace/bdn/venv/lib/python2.7/site-packages/bambou/contextual/context.py", line 44, in <lambda>
    lambda s: getattr(s.get(), name),
TypeError: Error when calling the metaclass bases
    'NoneType' object is not callable
```

**Comment by primalmotion** [comment]
Can you paste the output if pip freeze?

Thanks

**Comment by jjtykkyl** [comment]
bambou==1.0.0
coverage==4.0.3
Django==1.8.7
django-coverage-plugin==1.2.2
django-debug-toolbar==1.4
django-grappelli==2.7.3
django-simple-history==1.7.0
django-static-precompiler==1.1
djangorestframework==3.3.2
funcsigs==0.4
gunicorn==19.4.5
meld3==1.0.2
mock==1.3.0
npm==0.1.1
optional-django==0.1.0
pbr==1.8.1
Pillow==3.1.0
psycopg2==2.6.1
py2-ipaddress==3.4.1
requests==2.9.1
selenium==2.52.0
simple-history==1.1
six==1.10.0
splinter==0.7.3
sqlparse==0.1.18
supervisor==3.1.3
Unidecode==0.4.19
vspk==3.2.4.134
wheel==0.24.0

**Comment by primalmotion** [comment]
Should be ok... What version of Python, OS? Can you also provide a reduction (even if basic)?

Thanks

**Comment by jjtykkyl** [comment]
Python 2.7.5, Mac OS X 10.9. Can be reproduced by debugging any application with PyCharm and executing the following command:

```
from bambou.contextual import context
```

**Comment by primalmotion** [comment]
Does that also happen using the standard python interpreter? And does _not_ happen using iPython?

**Comment by jjtykkyl** [comment]
It doesn't occur with standard intrepreter, haven't tested with iPython

**Comment by primalmotion** [comment]
Do you mind trying with Bambou master (you can create a virtualenv, and do a pip install git+https://github.com/nuagenetworks/bambou.git)

**Comment by jjtykkyl** [comment]
We are trying to update the Nuage SDK itself, let's see if that solves the issue...
